#!/bin/bash

#
# Example service creation, including Traefic routing labels.
#
docker service create \
  --name md-validator-rails-poc \
  --hostname md-validator-rails-poc \
  --network traefik \
  --env ASSET_HOST="https://apps.iay.org.uk/md-validator-rails-poc" \
  --log-driver json-file --log-opt max-size=10m --log-opt max-file=3 \
  --constraint node.platform.arch==x86_64 \
  --constraint node.labels.type==general \
  --mount type=volume,source=rails-poc-logs,destination=/app/app/log \
  --label traefik.enable=true \
  --label traefik.http.services.rails-poc.loadbalancer.server.port=3000 \
  --label traefik.http.routers.rails-poc.entrypoints=websecure \
  --label traefik.http.routers.rails-poc.tls=true \
  --label traefik.http.routers.rails-poc.tls.certResolver=le \
  --label "traefik.http.routers.rails-poc.rule=Host(\`apps.iay.org.uk\`) && PathPrefix(\`/md-validator-rails-poc\`)" \
  --label traefik.http.routers.rails-poc.service=rails-poc \
  --with-registry-auth \
  registry.iay.org.uk/systems/misc/md-validator-rails-poc:latest
